### ISSUE TITLE
Possible to change port number?

### ISSUE THREAD

**Issue by romanpeters** [3choff/FastWhisperAPI#1]
Port 8000 is an often used port, and I’m already running another service on it. Is it possible to change the port used (without using Docker)?

**Comment by 3choff** [comment]
You can specify the port when you run the script. 

Example:

```bash
fastapi run main.py --port 5000
```
In this case, it will run on port 5000.

**Comment by romanpeters** [comment]
Must have overlooked that. Thanks!
