### ISSUE TITLE
How to change the default model ?

### ISSUE THREAD

**Issue by razvanab** [3choff/FastWhisperAPI#2]
I can't find a way to change the default model from base to another one.
I should have mentioned that I am trying to run FastWhisperAPI with this app:
https://github.com/PromtEngineer/Verbi

**Comment by 3choff** [comment]
To change the model, you just specify which model you want to use when making the request to the 'v1/transcriptions' endpoint in the payload (data). For example, this is a simple curl request to the API running on localhost using the large model:
```
curl -X POST "http://localhost:8000/v1/transcriptions" \
-H  "accept: application/json" \
-H  "Content-Type: multipart/form-data" \
-F "file=@audio1.wav;type=audio/wav" \
-F "model=large" \
-F "response_format=text" \" . 
```

The options are 'large', 'medium', 'small', 'base', 'tiny'.  

In the case of the Verbi project, the script handles the request in the elif model == 'fastwhisperapi': section of voice_assistant/transcription.py. To change the model, replace 'base' with the model of your choice in the 'data' section of the request.

Keep in mind that when changing the model, the first request will download the model, so it will take longer than the following requests with the same model.

**Comment by razvanab** [comment]
But how do you do it when using this command?
fastapi run main.py

I just need Fastapi to work in the background for Verbi.
https://github.com/PromtEngineer/Verbi

**Comment by 3choff** [comment]
The command "fastapi run main.py" is the command to run the script that launches the FastAPI not to query the endpoint. FastWhisperAPI and Verbi are independent of each other, and they run in separate terminals. 

Anyway, I invite you to address further queries regarding Verbi in its repository.

**Comment by razvanab** [comment]
Oh, I see. Thank you.
